services:
  mysql:
    image: mysql:8.0
    container_name: newjeans-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${SPRING_DATASOURCE_DB}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newjeans-spring-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Docker 실행 시 docker 프로파일 사용
    ports:
      - "8080:8080"

volumes:
  mysql_data:
#  redis_data:
