cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_BUCKET_ACCESS_KEY}
      secretKey: ${S3_BUCKET_SECRET_KEY}