spring:
  profiles:
    active: "local"
    group:
      test: "test"
      local: "local"
    include:
<<<<<<< HEAD
      - redis
      - security
=======
server:
  port: 8080
>>>>>>> 806c054 (feat: newsdata.io API 연동하여 기사 조회 기능 구현)
