spring:
  config:
    activate:
      on-profile: "docker"
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
    url: ${DOCKER_SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
