openai:
  api:
    uri: "https://api.groq.com/openai/v1/chat/completions"
    key: ${OPEN_AI_API_KEY}
  prompts:
    keyword-extraction: |
      아래에 여러 기사가 있음.
      각 기사에는 'articleId'와 기사 내용이 포함되어 있음.
      각 기사마다 핵심 키워드를 5개 추출하고, 아래 JSON 형식으로 반환해줘:
      
      {
        "articleId1": ["키워드1", "키워드2", "키워드3", "키워드4", "키워드5"],
        "articleId2": ["키워드1", "키워드2", "키워드3", "키워드4", "키워드5"], ... 
        "articleIdN": ["키워드1", "키워드2", "키워드3", "키워드4", "키워드5"]
      }
      
      반드시 JSON만 반환하고, 다른 설명이나 텍스트는 포함하지 마.


    role: "너는 한국어 텍스트에서 주요 키워드를 추출하는 도우미야."
    max-tokens: 100
    temperature: 0.5
