name: Build and Deploy to Develop

on:
  push:
    branches:
      - develop

env:
  DOCKERHUB_USERNAME: swp0927
  DOCKERHUB_IMAGE_NAME: newjeans-server

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      #- name: Start Redis container for test
      #  run: docker compose -f ./docker-compose-test.yml up -d


      ## create .env
      - name: make .env
        run: |
          touch ./.env
          echo "${{ secrets.ENVIRONMENTS }}" >> ./.env
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test -x spotlessCheck

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Extract metadata for Docker
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE_NAME }}
          tags: |
            type=sha,prefix=

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          IMAGE_FULL_URL: ${{ steps.metadata.outputs.tags }}
          DOCKERHUB_IMAGE_NAME: ${{ env.DOCKERHUB_IMAGE_NAME }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE_FULL_URL, DOCKERHUB_IMAGE_NAME
          script: |
            sudo docker-compose down
            sudo docker-compose up -d
            sudo docker image prune -f
